## Artificial neural network example, classification, diabetes dataset

In [1]:
# first neural network with keras tutorial
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix


ModuleNotFoundError: No module named 'tensorflow'

In [2]:
ds = pd.read_csv('datasets_228_482_diabetes_nh.csv')
X = ds.iloc[:, 0:8].values
y = ds.iloc[:,8 ].values
Xtr, Xtst, ytr, ytst = train_test_split(X, y, test_size=0.2 )

In [3]:
print(Xtr)

[[0.00e+00 1.62e+02 7.60e+01 ... 4.96e+01 3.64e-01 2.60e+01]
 [2.00e+00 1.55e+02 7.40e+01 ... 2.66e+01 4.33e-01 2.70e+01]
 [6.00e+00 1.14e+02 8.80e+01 ... 2.78e+01 2.47e-01 6.60e+01]
 ...
 [5.00e+00 1.04e+02 7.40e+01 ... 2.88e+01 1.53e-01 4.80e+01]
 [5.00e+00 1.15e+02 9.80e+01 ... 5.29e+01 2.09e-01 2.80e+01]
 [2.00e+00 1.21e+02 7.00e+01 ... 3.91e+01 8.86e-01 2.30e+01]]


In [4]:
# define the keras model
model = Sequential()
model.add(Dense(15, input_dim=8, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
print(type(model))

<class 'keras.engine.sequential.Sequential'>


In [5]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit the keras model on the dataset
model.fit(Xtr, ytr, epochs=200, batch_size=10)
# evaluate the keras model
_, accuracy = model.evaluate(Xtst, ytst, verbose=0)
print('Accuracy: %.2f ' % (accuracy*100))


Epoch 1/200
62/62 [==============================] - 0s 589us/step - loss: 10.1998 - accuracy: 0.4356
Epoch 2/200
62/62 [==============================] - 0s 638us/step - loss: 2.1899 - accuracy: 0.6297
Epoch 3/200
62/62 [==============================] - 0s 572us/step - loss: 1.7702 - accuracy: 0.6101
Epoch 4/200
62/62 [==============================] - 0s 589us/step - loss: 1.4039 - accuracy: 0.6444
Epoch 5/200
62/62 [==============================] - 0s 621us/step - loss: 1.0121 - accuracy: 0.6444
Epoch 6/200
62/62 [==============================] - 0s 589us/step - loss: 0.7772 - accuracy: 0.6607
Epoch 7/200
62/62 [==============================] - 0s 621us/step - loss: 0.6998 - accuracy: 0.6705
Epoch 8/200
62/62 [==============================] - 0s 638us/step - loss: 0.6887 - accuracy: 0.6737
Epoch 9/200
62/62 [==============================] - 0s 589us/step - loss: 0.6666 - accuracy: 0.6737
Epoch 10/200
62/62 [==============================] - ETA: 0s - loss: 0.7660 - accuracy: 0

Epoch 81/200
62/62 [==============================] - 0s 719us/step - loss: 0.5099 - accuracy: 0.7569
Epoch 82/200
62/62 [==============================] - 0s 540us/step - loss: 0.5327 - accuracy: 0.7292
Epoch 83/200
62/62 [==============================] - 0s 719us/step - loss: 0.4937 - accuracy: 0.7586
Epoch 84/200
62/62 [==============================] - 0s 670us/step - loss: 0.4977 - accuracy: 0.7488
Epoch 85/200
62/62 [==============================] - 0s 687us/step - loss: 0.5199 - accuracy: 0.7439
Epoch 86/200
62/62 [==============================] - 0s 540us/step - loss: 0.4958 - accuracy: 0.7488
Epoch 87/200
62/62 [==============================] - 0s 703us/step - loss: 0.5063 - accuracy: 0.7602
Epoch 88/200
62/62 [==============================] - 0s 540us/step - loss: 0.4893 - accuracy: 0.7423
Epoch 89/200
62/62 [==============================] - 0s 638us/step - loss: 0.4934 - accuracy: 0.7455
Epoch 90/200
62/62 [==============================] - 0s 605us/step - loss: 0.4923

In [6]:
yprd = model.predict(Xtst)
print(yprd)   b

[[0.33258057]
 [0.85760653]
 [0.43432432]
 [0.5374547 ]
 [0.36512953]
 [0.5751519 ]
 [0.5400812 ]
 [0.06944674]
 [0.16806185]
 [0.20132735]
 [0.19624484]
 [0.8778235 ]
 [0.01785639]
 [0.42487645]
 [0.24196404]
 [0.2239713 ]
 [0.3858208 ]
 [0.5305829 ]
 [0.27817908]
 [0.20788613]
 [0.47219542]
 [0.9190532 ]
 [0.29079467]
 [0.20794263]
 [0.00403926]
 [0.35678592]
 [0.11152461]
 [0.32364196]
 [0.06573641]
 [0.3571216 ]
 [0.9590948 ]
 [0.21111909]
 [0.3385172 ]
 [0.14374581]
 [0.10146657]
 [0.09724283]
 [0.45795673]
 [0.8543409 ]
 [0.27905816]
 [0.45850363]
 [0.08072376]
 [0.6555642 ]
 [0.52963984]
 [0.35043555]
 [0.24905652]
 [0.52941746]
 [0.981416  ]
 [0.40059054]
 [0.86163056]
 [0.70876193]
 [0.90296316]
 [0.2896248 ]
 [0.27167553]
 [0.60639656]
 [0.28322947]
 [0.6744194 ]
 [0.16815862]
 [0.33583963]
 [0.42663568]
 [0.215922  ]
 [0.05212077]
 [0.42136624]
 [0.6290458 ]
 [0.99007106]
 [0.30273592]
 [0.43373466]
 [0.9585068 ]
 [0.9922004 ]
 [0.19796881]
 [0.33411646]
 [0.00611344]
 [0.63

In [7]:
yprd = np.round(yprd,0)
print(yprd,'\n\n\n')
print(confusion_matrix(ytst, yprd))
print('\n\n', classification_report(ytst, yprd))

[[0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]] 



[[79 14]
 [26 35]]


               precision    recall  f1-score   sup